# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
