# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_pokemon_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
